name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '28 20 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: "javascript"
    - name: Setup Node
      uses: actions/setup-node@v3.0.0
    - name: Prepare Node
      run: npm ci
    - name: Build Node
      run: npm build
    - name: Analyze CodeQL
      uses: github/codeql-action/analyze@v1
