name: React

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
    - name: Checkout Git
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
        cache: 'npm'
    - name: Prepare Node
      run: npm ci
    - name: Deploy Node
      run: npm run deploy
